import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import warnings
from pathlib import Path
from data_loader import DataLoader
from signals import Layer1MacroEngine, Layer2OnchainEngine, Layer3PolymarketEngine, SignalAggregator
from risk_manager import KellyATRSizer, StopLossManager, ExecutionSplitter, RiskCircuitBreaker

warnings.filterwarnings('ignore')

class Backtester:
    def __init__(self, data: pd.DataFrame, config: dict = None):
        self.data = data
        self.capital = 100000.0
        
        self.config = config or {
            'trade_cost': 0.0006,  # 6 bps
            'max_daily_delta_change': 0.25,
            'target_vol': 0.50
        }
        
        # --- Modules Initialization ---
        self.l1 = Layer1MacroEngine()
        self.l2 = Layer2OnchainEngine()
        self.l3 = Layer3PolymarketEngine()
        self.aggregator = SignalAggregator(target_vol=self.config['target_vol'])
        
        self.kelly = KellyATRSizer()
        self.stop_mgr = StopLossManager()
        self.circuit_breaker = RiskCircuitBreaker()
        
        # --- Tracking ---
        self.equity_curve = []
        self.target_exposures = []
        self.actual_exposures = []
        
        self.current_equity = self.capital
        self.max_equity = self.capital
        self.current_exposure = 0.0
        
        # State
        self.recent_returns = []
        
    def _precompute_signals(self):
        print("⚙️ Precomputing Signals (Layers 1-3)...")
        df = self.data
        df = self.l1.compute(df)
        df = self.l2.compute(df)
        df = self.l3.compute(df)
        
        # Drop NaNs generated by rolling windows
        self.data = df.dropna().copy()
        print(f"   Data points ready: {len(self.data)}")

    def run(self):
        self._precompute_signals()
        
        print("🚀 Starting Backtest with Kelly-ATR & Circuit Breakers...")
        
        for i in range(len(self.data)):
            row = self.data.iloc[i]
            
            # --- 1. Process PnL from PREVIOUS day's exposure ---
            prev_equity = self.current_equity # Save it BEFORE adding trade_pnl
            if i > 0:
                ret = row['returns']
                trade_pnl = self.current_exposure * prev_equity * ret
                self.current_equity += trade_pnl
                self.max_equity = max(self.max_equity, self.current_equity)
                
                if len(self.target_exposures) > 0 and self.target_exposures[-1] != 0:
                    sig_ret = ret * np.sign(self.target_exposures[-1])
                    self.recent_returns.append(sig_ret)
                else:
                    self.recent_returns.append(0)
                    
                if len(self.recent_returns) > 60:
                    self.recent_returns.pop(0)
            
            # Record current state
            self.equity_curve.append(self.current_equity)
            self.actual_exposures.append(self.current_exposure)
            
            # --- 1.5 ATR Stop-Loss & Take-Profit Check (Intraday High/Low) ---
            # We only check triggers if we have an active position from the previous day.
            if self.current_exposure != 0 and hasattr(self, 'active_stop_price'):
                direction = np.sign(self.current_exposure)
                # Check if high/low hit the stop/tp levels
                trigger_type, trigger_price, close_pct = self.stop_mgr.check_triggers(
                    bar_high=row['high'], 
                    bar_low=row['low'], 
                    direction=direction, 
                    stop_price=self.active_stop_price, 
                    tp_prices=self.active_tp_prices
                )
                
                if trigger_type == 'stop':
                    # Full close
                    # We assume execution happened at the stop price
                    prev_close = row['close'] / (1 + row['returns']) if row['returns'] != -1 else row['close']
                    trigger_ret = (trigger_price - prev_close) / prev_close if prev_close > 0 else 0
                    
                    # Correct the PnL: subtract the wrong close-based PnL, add the correct trigger_price-based PnL
                    wrong_pnl = self.current_exposure * prev_equity * row['returns']
                    correct_pnl = self.current_exposure * prev_equity * trigger_ret
                    self.current_equity += (correct_pnl - wrong_pnl)
                    
                    self._update_exposure(0.0)
                    self.target_exposures.append(0.0)
                    # We broke out of the active position, continue to next bar or wait for new signal
                    continue
                elif trigger_type and trigger_type.startswith('tp'):
                    # Partial close
                    prev_close = row['close'] / (1 + row['returns']) if row['returns'] != -1 else row['close']
                    trigger_ret = (trigger_price - prev_close) / prev_close if prev_close > 0 else 0
                    
                    # Correct the PnL for the portion that was closed
                    closed_exposure = self.current_exposure * close_pct
                    wrong_pnl = closed_exposure * prev_equity * row['returns']
                    correct_pnl = closed_exposure * prev_equity * trigger_ret
                    self.current_equity += (correct_pnl - wrong_pnl)
                    
                    # Reduce exposure by the close_pct
                    new_exp = self.current_exposure * (1 - close_pct)
                    self._update_exposure(new_exp)
            
            # --- 2. Risk Circuit Breaker ---
            daily_pnl_pct = (self.current_equity - self.equity_curve[-2]) / self.equity_curve[-2] if i > 0 else 0
            allow_trading, dd_multiplier, reason = self.circuit_breaker.check(
                self.current_equity, self.max_equity, daily_pnl_pct, row['vix']
            )
            
            if not allow_trading:
                # Force close all
                self._update_exposure(0.0)
                self.target_exposures.append(0.0)
                continue
                
            # --- 3. Compute Raw Target Exposure (Aggregator) ---
            raw_target, raw_z = self.aggregator.compute(
                l1_z=row['l1_z'],
                l2_z=row['l2_z'],
                l3_z=row['l3_z'],
                l4_z=row['narrative_score'],
                vix=row['vix'],
                btc_vol=row['btc_vol_30d'],
                dd_from_high=row['dd_from_20d_high']
            )
            
            # Apply drawdown modifier
            target_exposure = raw_target * dd_multiplier
            
            # --- 4. Kelly-ATR Position Sizing ---
            if target_exposure != 0:
                # Calculate Kelly Cap
                kelly_cap = self.kelly.compute(
                    np.array(self.recent_returns), row['atr_14'], row['close']
                )
                
                # Constrain target exposure by Kelly Cap
                if target_exposure > 0:
                    target_exposure = min(target_exposure, kelly_cap)
                else:
                    target_exposure = max(target_exposure, -kelly_cap)
            
            self.target_exposures.append(target_exposure)
            
            # --- 5. Exposure Smoothing (Max Daily Delta Change) ---
            delta_diff = target_exposure - self.current_exposure
            max_change = self.config['max_daily_delta_change']
            
            if delta_diff > max_change:
                actual_target = self.current_exposure + max_change
            elif delta_diff < -max_change:
                actual_target = self.current_exposure - max_change
            else:
                actual_target = target_exposure
                
            # --- 6. Set New Stop-Loss & Take-Profit Levels if entering a new position ---
            # If our direction changes, or we go from 0 to non-zero, calculate new stops based on entry price
            if actual_target != 0 and (np.sign(actual_target) != np.sign(self.current_exposure) or self.current_exposure == 0):
                stop_price, tp_prices = self.stop_mgr.compute_levels(
                    entry_price=row['close'], 
                    atr=row['atr_14'], 
                    direction=np.sign(actual_target)
                )
                self.active_stop_price = stop_price
                self.active_tp_prices = tp_prices
                
            # Update exposure and deduct costs
            self._update_exposure(actual_target)
            
        # Add tracking data back to dataframe
        self.data['strategy_equity'] = self.equity_curve
        self.data['strategy_exposure'] = self.actual_exposures
        self.data['target_exposure'] = self.target_exposures
        self.data['bh_equity'] = (1 + self.data['returns']).cumprod() * self.capital
        
        return self.data
        
    def _update_exposure(self, new_exposure):
        turnover = abs(new_exposure - self.current_exposure)
        cost = turnover * self.current_equity * self.config['trade_cost']
        self.current_equity -= cost
        self.current_exposure = new_exposure

    def summary(self):
        df = self.data
        strat_returns = df['strategy_equity'].pct_change().dropna()
        bh_returns = df['bh_equity'].pct_change().dropna()
        
        strat_total = (df['strategy_equity'].iloc[-1] / self.capital) - 1
        bh_total = (df['bh_equity'].iloc[-1] / self.capital) - 1
        
        strat_ann_vol = strat_returns.std() * np.sqrt(365)
        bh_ann_vol = bh_returns.std() * np.sqrt(365)
        
        strat_sharpe = strat_returns.mean() / strat_returns.std() * np.sqrt(365) if strat_returns.std() != 0 else 0
        bh_sharpe = bh_returns.mean() / bh_returns.std() * np.sqrt(365) if bh_returns.std() != 0 else 0
        
        strat_mdd = (df['strategy_equity'] / df['strategy_equity'].cummax() - 1).min()
        bh_mdd = (df['bh_equity'] / df['bh_equity'].cummax() - 1).min()
        
        # Win Rate
        wins = len(strat_returns[strat_returns > 0])
        losses = len(strat_returns[strat_returns < 0])
        win_rate = wins / (wins + losses) if (wins + losses) > 0 else 0
        
        # Profit Factor
        gross_profit = strat_returns[strat_returns > 0].sum()
        gross_loss = abs(strat_returns[strat_returns < 0].sum())
        profit_factor = gross_profit / gross_loss if gross_loss != 0 else float('inf')
        
        # Calmar Ratio
        strat_ann_ret = (1 + strat_total) ** (365 / len(df)) - 1
        calmar = strat_ann_ret / abs(strat_mdd) if strat_mdd != 0 else float('inf')
        
        print("\n" + "="*50)
        print("📊 STRATEGY PERFORMANCE SUMMARY")
        print("="*50)
        print(f"{'Metric':<20} | {'Strategy':<12} | {'Buy & Hold':<12}")
        print("-" * 50)
        print(f"{'Total Return':<20} | {strat_total:>11.2%} | {bh_total:>11.2%}")
        print(f"{'Ann. Volatility':<20} | {strat_ann_vol:>11.2%} | {bh_ann_vol:>11.2%}")
        print(f"{'Sharpe Ratio':<20} | {strat_sharpe:>11.2f} | {bh_sharpe:>11.2f}")
        print(f"{'Max Drawdown':<20} | {strat_mdd:>11.2%} | {bh_mdd:>11.2%}")
        print(f"{'Calmar Ratio':<20} | {calmar:>11.2f} | -")
        print(f"{'Win Rate (Daily)':<20} | {win_rate:>11.2%} | -")
        print(f"{'Profit Factor':<20} | {profit_factor:>11.2f} | -")
        print("="*50)
        
        self._plot()
        
    def _plot(self):
        df = self.data
        fig, axes = plt.subplots(3, 1, figsize=(14, 15), gridspec_kw={'height_ratios': [2, 1, 1]})
        
        # 1. Equity
        axes[0].plot(df.index, df['strategy_equity'], label='Strategy', color='blue', linewidth=2)
        axes[0].plot(df.index, df['bh_equity'], label='Buy & Hold', color='orange', alpha=0.7)
        axes[0].set_title('Strategy vs Buy & Hold (Equity Curve)', fontsize=14)
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)
        
        # 2. Exposure
        axes[1].fill_between(df.index, 0, df['strategy_exposure'], 
                             where=df['strategy_exposure']>=0, color='green', alpha=0.5, label='Long')
        axes[1].fill_between(df.index, 0, df['strategy_exposure'], 
                             where=df['strategy_exposure']<0, color='red', alpha=0.5, label='Short')
        axes[1].plot(df.index, df['strategy_exposure'], color='black', linewidth=1, label='Actual Exposure')
        axes[1].plot(df.index, df['target_exposure'], color='blue', linestyle=':', alpha=0.5, label='Target (Raw)')
        axes[1].set_title('Dynamic Exposure (Kelly & Smooth constrained)', fontsize=14)
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)
        
        # 3. Z-Scores
        axes[2].plot(df.index, df['l1_z'], label='L1 Z-Score', alpha=0.6)
        axes[2].plot(df.index, df['l2_z'], label='L2 Z-Score', alpha=0.6)
        axes[2].plot(df.index, df['l3_z'], label='L3 Z-Score', alpha=0.6)
        axes[2].axhline(0, color='black', linestyle='--', linewidth=1)
        axes[2].set_title('Signals Breakdown', fontsize=14)
        axes[2].legend()
        axes[2].grid(True, alpha=0.3)
        
        plt.tight_layout()
        chart_path = Path(__file__).parent / 'comprehensive_report.png'
        plt.savefig(chart_path, dpi=150)
        print(f"\n✅ Visual report saved to {chart_path}")

if __name__ == "__main__":
    loader = DataLoader(start_date="2023-01-01", end_date="2026-05-01", csv_path=Path(__file__).parent / "user_real_data.csv")
    df = loader.fetch_data()
    
    bt = Backtester(df)
    res_df = bt.run()
    bt.summary()
    
    res_df.to_csv(Path(__file__).parent / 'backtest_results.csv')
    print("✅ Backtest results exported to backtest_results.csv")
